language: java

jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
  - $HOME/.m2

install: true

script:
  - jdk_switcher use openjdk8
  - java -version
  - cd Calculator
  - mvn -Dsurefire.printSummary=false -q clean package
  - mvn cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)
  - jdk_switcher use openjdk11
  - java -version
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=kuesugi -Dsonar.login=e320eb28e1c47b43940386bd4d13b372d5c93f3c