language: java

jdk: openjdk8

cache:
  directories:
  - $HOME/.m2

install: true

script:
  - java -version
  - cd Calculator
  - mvn clean package
  - mvn sonar:sonar
 # - mvn -Dtest=CalculatorSpec test

addons:
  sonarcloud:
    organization: 'kuesugi'
    token: 'e320eb28e1c47b43940386bd4d13b372d5c93f3c'