language: java

jdk: openjdk8

cache:
  directories:
  - $HOME/.m2

install: true

script:
  - java -version
  - cd Calculator
  - mvn clean install
  - mvn -Dtest=CalculatorSpec -Dsurefire.printSummary=false -q test
  - mvn cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)