dist: xenial

language: java

jdk: 
  - openjdk8
  - openjdk11

cache:
  directories:
  - $HOME/.m2

install: true

script:
  - java -version
  - cd Calculator
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=kuesugi_calculator
  - mvn -Dtest=CalculatorSpec test

addons:
  sonarcloud:
    organization: 'kuesugi'
    token: 'e320eb28e1c47b43940386bd4d13b372d5c93f3c'