language: java

jdk: openjdk8

cache:
  directories:
  - $HOME/.m2

install: true

script:
  - java -version
  - cd Calculator
  - mvn -Dsurefire.printSummary=false -q clean install
  - mvn cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)