language: java

jdk: openjdk11

cache:
  directories:
  - $HOME/.m2

install: true

script:
  - java -version
  - cd Calculator
  - mvn package
 # - mvn sonar:sonar -Dsonar.projectKey=kuesugi_calculator
  - cd target && ls && cd ..
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=kuesugi -Dsonar.login=e320eb28e1c47b43940386bd4d13b372d5c93f3c
 # - mvn -Dtest=CalculatorSpec test