language: java

jdk: openjdk11

cache:
  directories:
  - $HOME/.m2

install: true

script:
  - java -version
  - cd Calculator
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report
  - if [ "$JAVA_HOME" = "/usr/local/lib/jvm/openjdk11" ]; then mvn sonar:sonar; fi
  - mvn -Dtest=CalculatorSpec test

addons:
  sonarcloud:
    organization: 'kuesugi'
    token: 'e320eb28e1c47b43940386bd4d13b372d5c93f3c'